BaseUrl= "https://cerisara.github.io/xtofsite/"
LanguageCode= "fr-FR"
Title= "Xtofification"
theme = "hugo-theme-casper"
paginate = 5
DisqusShortname = "xtof"
Copyright = "All rights reserved - 2015"
canonifyurls = true

[params]
  description = "Geek, geocacher, clarinetist"
  cover = "images/cover.jpg"
  author = "xtof54"
  authorlocation = "Nancy, France"
  authorwebsite = "https://cerisara.github.io/xtofsite/"
  bio= "Geek, geocacher, clarinetist"
  logo = "images/me.jpg"
  googleAnalyticsUserID = "UA-32463045-4"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  # RSSLink = "http://feeds.feedburner.com/..." 
  githubName = "cerisara"
  twitterName = "ccerisara"
  # facebookName = ""
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

